"""add_asset_cert_algo_finding_tables

Revision ID: 34cb0c0e22bc
Revises: 61bc0e3f062b
Create Date: 2026-06-03 21:28:28.943281

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "34cb0c0e22bc"
down_revision = "61bc0e3f062b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum(
                "server",
                "endpoint",
                "network_device",
                "load_balancer",
                "vpn_gateway",
                "database",
                "web_app",
                "api",
                "container",
                "kubernetes_cluster",
                "cloud_resource",
                "hsm",
                "kms",
                "certificate_authority",
                "smart_card",
                "firmware",
                "saas",
                "other",
                name="asset_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("fqdn", sa.String(length=500), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=20), nullable=True),
        sa.Column("os", sa.String(length=100), nullable=True),
        sa.Column(
            "environment",
            sa.Enum(
                "production",
                "staging",
                "development",
                "testing",
                "unknown",
                name="asset_env_enum",
                native_enum=False,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("business_service", sa.String(length=255), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("discovery_source", sa.String(length=50), nullable=True),
        sa.Column("first_scan_id", sa.UUID(), nullable=True),
        sa.Column("last_scan_id", sa.UUID(), nullable=True),
        sa.Column(
            "first_discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("cmdb_ci_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["first_scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_scan_id"],
            ["scans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "algorithms",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("algorithm_name", sa.String(length=100), nullable=False),
        sa.Column(
            "algorithm_type",
            sa.Enum(
                "key_exchange",
                "signature",
                "symmetric",
                "hash",
                "mac",
                "kem",
                "composite",
                name="algo_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("key_size", sa.Integer(), nullable=True),
        sa.Column("curve", sa.String(length=50), nullable=True),
        sa.Column("protocol", sa.String(length=50), nullable=True),
        sa.Column("protocol_version", sa.String(length=20), nullable=True),
        sa.Column("cipher_suite", sa.String(length=200), nullable=True),
        sa.Column(
            "pqc_status",
            sa.Enum(
                "vulnerable",
                "transitioning",
                "hybrid",
                "pqc_ready",
                "safe",
                name="algo_pqc_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "is_quantum_vulnerable",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("oid", sa.String(length=100), nullable=True),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "certificates",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("thumbprint", sa.String(length=128), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("serial_number", sa.String(length=128), nullable=True),
        sa.Column("sig_algorithm", sa.String(length=100), nullable=False),
        sa.Column("pub_key_algorithm", sa.String(length=100), nullable=False),
        sa.Column("pub_key_size", sa.Integer(), nullable=True),
        sa.Column("curve_name", sa.String(length=50), nullable=True),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("not_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "is_self_signed", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("is_ca", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("key_usage", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("san_dns", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("san_ip", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("pqc_capable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "pqc_details", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("chain_position", sa.String(length=20), nullable=True),
        sa.Column("ca_thumbprint", sa.String(length=128), nullable=True),
        sa.Column("raw_certificate", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "finding_type",
            sa.Enum(
                "weak_algorithm",
                "weak_key_size",
                "tls_version",
                "pqc_not_supported",
                "pqc_downgrade",
                "cert_expiring",
                "cert_expired",
                "self_signed",
                "unknown_ca",
                "ssh_weak_kex",
                "ssh_weak_host_key",
                "vpn_weak_ike",
                "hsm_vulnerable",
                "kms_vulnerable",
                "code_weak_crypto",
                "sbom_vulnerable_lib",
                "config_drift",
                "other",
                name="finding_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "info",
                name="severity_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("algorithm", sa.String(length=100), nullable=True),
        sa.Column("algorithm_type", sa.String(length=30), nullable=True),
        sa.Column("pqc_status", sa.String(length=20), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column(
            "hndl_exposure",
            sa.Enum(
                "high",
                "medium",
                "low",
                "none",
                name="hndl_exposure_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("remediation", sa.Text(), nullable=True),
        sa.Column("recommended_algorithm", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "resolved",
                "accepted",
                "false_positive",
                name="finding_status_enum",
                native_enum=False,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("ticket_id", sa.String(length=255), nullable=True),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("findings")
    op.drop_table("certificates")
    op.drop_table("algorithms")
    op.drop_table("assets")
    # ### end Alembic commands ###
