"""add_scan_logs_table

Revision ID: 61bc0e3f062b
Revises: 3901ade057dc
Create Date: 2026-06-03 20:57:10.826918

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "61bc0e3f062b"
down_revision = "3901ade057dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "debug",
                "info",
                "warn",
                "error",
                "fatal",
                name="log_level_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("phase", sa.String(length=30), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scan_logs")
    # ### end Alembic commands ###
